// Autogenerated by Thrift Compiler (0.9.1)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package spcms

import (
	"fmt"
	"math"
	"thrift"
	"github.com/thriftlib/cms"

)

// (needed to ensure safety because of naive import list construction.)
var _ = math.MinInt32
var _ = thrift.ZERO
var _ = fmt.Printf

var _ = cms.GoUnusedProtection__

func init() {
}

